version: 2

models:
  - name: fact_page_views
    description: Combination of order, user,  promo, and order items
  - name: fact_session_funnel
    description: Shows count of sessions and how they are progressing through the funnel